apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-operator
  namespace: argocd
spec:
  project: platform-components
  source:
    repoURL: https://charts.crossplane.io/stable
    chart: crossplane
    targetRevision: 2.0.2
    helm:
      valuesFiles:
        - values.yaml
  destination:
    server: https://51EC70937828D58D36BEA4C848D1B47F.sk1.us-east-1.eks.amazonaws.com
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true