apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: platform-components
  source:
    repoURL: https://charts.crossplane.io/stable
    chart: crossplane
    targetRevision: 2.0.2
    # helm:
    #   values: |
    #     args:
    #       - --enable-composition-revisions
    #     resources:
    #       limits:
    #         cpu: 500m
    #         memory: 512Mi
    #       requests:
    #         cpu: 250m
    #         memory: 256Mi
  destination:
    name: in-cluster
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - Replace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
