apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kratix-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: platform-components
  source:
    repoURL: https://github.com/hogonzalezve/platform-infra.git
    targetRevision: main
    path: apps/20-platform/kratix/controller
    kustomize: {}
  destination:
    name: in-cluster
    namespace: kratix-platform-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
