apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pin the Kratix release instead of 'latest' for repeatable installs
  - https://github.com/syntasso/kratix/releases/download/v0.32.0/kratix.yaml
