# platform-components/catalog/identity.yaml
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-team
  description: Equipo de Plataforma
spec:
  type: team
  profile:
    displayName: Platform Team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: platform
  description: Sistema de Plataforma (infra y controladores)
  tags: [platform, infra, argocd, crossplane, kratix]
spec:
  owner: group:platform-team
