apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-infrastructure
  namespace: argocd
spec:
  project: platform-infrastructure
  source:
    repoURL: https://github.com/hogonzalezve/platform-infrastructure.git
    targetRevision: main
    path: 30-infrastructure/manifests
  destination:
    server: in-cluster
    namespace: platform-infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
