apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: crossplane-provider-aws
  namespace: crossplane-system
spec:
  serviceAccountTemplate:
    metadata:
      name: crossplane-provider-aws
